### ISSUE TITLE
Backup job data on test server

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/issues#10]
Make a cronjob for backing up job data. Also check that job data is handled correctly on a apt-get upgrade.

Related:
- [x] https://github.com/daisy/pipeline-webui/issues/23

**Comment by bertfrees** [comment]
Backing up of web UI data is currently done in snaekobbi/test-server-hubot at [bash/handlers/pipeline-upgrade#L10](https://github.com/snaekobbi/test-server-hubot/blob/bdb7a44b0ac7f60664ff34d982295a209fa8a8d1/bash/handlers/pipeline-upgrade#L10). Server data is not explicitly backed up. In fact for the latest system update I changed the script to [remove the data directory](https://github.com/snaekobbi/system/commit/2fb7ab5d8d6f96e1d501f6c8b4a7458a3d5abca3) because of an incompatibility caused by changes in a database table.

The question is whether removing the data directory should be the default behavior or not? If not, we should check that data is not removed with a `apt-get upgrade` nor with a `dpkg -i` (as it's currently done in snaekobbi/system).

@josteinaj: Another question is whether the web UI even needs the server to persist job data since it stores some job data itself.

**Comment by josteinaj** [comment]
The Web UI does not store much job data itself, it mainly just references the underlying engine job: https://github.com/daisy/pipeline-webui/blob/big-update/conf/evolutions/default/6.sql#L7

If we start storing job data in the Web UI then we essentially reduce the engine to an XProc engine. Which I'd probably be fine with, but it would mean we can't access the same jobs across clients (which we probably don't need anyway). Going that path would kind of mean going away from the client/server approach to DP2 I think, and we might as well use the engine as a library the same way as the GUI does instead of as a separate process.

I don't know, this seems to be part of the bigger discussion about what should be the responsibility of the client and what should be the responsibility of the engine...

As for the default behavior; as a user I would expect the default behavior to be _not_ to remove the data directory when upgrading. If there is an incompatibility in the DB tables, then either use an evolution mechanism like the one built into the Play framework, or maybe increase the major version of the engine whenever the table changes (i.e. consider it a breaking change), and delete the data directory only in those cases (preferably with a warning prompt).

**Comment by bertfrees** [comment]
OK. No I didn't mean going away from the client/server approach. I just thought the web UI already did safe quite a bit of job data. Maybe it's just the input files it safes?

What you say about the default behavior makes sense.

**Comment by josteinaj** [comment]
Oh, you're right. Yeah I guess it does store quite a bit now with the ability to rerun jobs and all - it's just not stored in the DB. The only thing not stored in the Web UI are the result files.
