### ISSUE TITLE
Add datatypes to scripts

### ISSUE THREAD

**Issue by josteinaj** [snaekobbi/issues#20]
Create and start using in scripts:
- enumerated values
- regexes

**Comment by bertfrees** [comment]
OK. @usama49 could you maybe have a look at this?

The MTM script (https://github.com/snaekobbi/pipeline-mod-mtm/blob/master/src/main/resources/xml/dtbook-to-pef.xpl) has some use cases for enumerated values and regexes.

For example, the following option, which is currently a boolean could be changed into an enum, so that the name and description of the option becomes more natural:

``` xml
<p:option name="single-line-spacing" required="false" px:type="boolean" select="'true'">
   <p:documentation>
      <h2 px:role="name">Single line spacing</h2>
      <p px:role="desc">Select 'No' for double line spacing.</p>
   </p:documentation>
</p:option>
```

becomes:

``` xml
<p:option name="line-spacing" required="false" px:type="string" px:data-type="mtm:line-spacing" select="'single'">
   <p:documentation>
      <h2 px:role="name">Line spacing</h2>
      <p px:role="desc">'single' or 'double' line spacing.</p>
   </p:documentation>
</p:option>
```

The enum data type `mtm:line-spacing` will have to be defined somewhere. https://github.com/daisy/pipeline-framework/pull/84 explains how to do this. A file called e.g. `resources/xml/data-types/line-spacing.xml` could contain the following:

``` xml
<values id="mtm:line-spacing">
   <value>single</value>
   <value>double</value>
</values>
```

and `resources/META-INF/catalog.xml` would need the following entry:

``` xml
  <uri name="http://www.mtm.se/pipeline/modules/braille/data-types/line-spacing.xml"
       uri="../xml/data-types/line-spacing.xml" px:data-type="true"/>
```

In this enum example we used an invented syntax. I would have loved to have something more standard and generic, but nobody is that enthusiastic about my RelaxNG proposal so for now I guess we just try this. This means that we should also invent a new syntax for defining regex data-types. What about the following?

``` xml
<regex id="..." pattern="..."/>
```

Joel gave me an example use case the other day but I'm not sure for which option it is supposed to be used. I don't see it in http://sourceforge.net/p/daisymfc/code/HEAD/tree/trunk/dmfc/scripts/create_distribute/pef/DTBookToPEF.taskScript either:

``` xml
<regex id="mtm:p-nummer" pattern="P[0-9]{5}"/>
```

@joeha480?

**Comment by bertfrees** [comment]
By the way, in order to properly support descriptions of enum (or boolean) values we could consider a syntax similar to that of Pipeline 1. Right now the nicename which is presented in the UI and the value which is used in the script are one and the same.

``` xml
<enum>
   <item nicename="32 characters wide" value="A4-w32" />
   <item nicename="32 characters wide (double line spacing)" value="A4-w32-dls" />
   <item nicename="42 characters wide" value="FA44-w42" />
   <item nicename="50 characters wide" value="w50" />
</enum>
```

**Comment by josteinaj** [comment]
> I would have loved to have something more standard and generic, but nobody is that enthusiastic about my RelaxNG proposal so for now I guess we just try this.

I usually like Relax NG, but in this case it seems to put too many requirements on the client implementation. I don't know how you would map a generic Relax NG structure to a Web UI widget? However, we could maybe use a subset of Relax NG. I'll give it a try:

Enums in RelaxNG:

``` xml
<choice>
    <value>single</value>
    <value>double</value>
</choice>
```

Regex in RelaxNG:

``` xml
<data type="string">
    <param name="pattern">\d</param>
</data>
```
- The `type` attribute on the `data` element is redundant as that is declared in the script, so we could just drop that one
- There is no `id` in RelaxNG, but I guess we could just add it anyway; alternatively move it to catalog.xml
- There's no real need for `<list>`, `<interleave>` etc, as we have `sequence` and `ordered` in the scripts
- `<a:documentation>` could maybe be used as a nicename for values, but it's not allowed inside the `<value>` elements

The three different versions are after all pretty similar though:

**enum:**
- `/values[@id]/value/text()` (current proposal)
- `/choice[@id]/value/text()` (Relax NG + root `@id`)
- `/enum[@id]/item[@nicename | @value]` (Pipeline 1 + root `@id`)

**regex/pattern:**
- `/regex[@id | @pattern]` (your current proposal)
- `/data[@id]/param[@name='pattern']/text()` (Relax NG + root `@id`)
- `/string[@id | @regex]` (Pipeline 1 + root `@id`)

I could easily add support for them all at the same time in the Web UI (although we should probably pick one). I have a slight preference for the first options (`/values` and `/regex`), but I'm open for other suggestions as well.

**Comment by josteinaj** [comment]
Actually, re-reading your [last couple of comments in daisy/pipeline-framework#84](https://github.com/daisy/pipeline-framework/pull/84#issuecomment-143314554) you have much better suggestions about how to do it in Relax NG than my thoughts above.

My main concern is that it must be easy for the Web UI to parse and do something with the datatypes. If you have a suggestion on how to do it in a way that is valid Relax NG (plus a root `id` attribute for now), then I would probably be up for that.

**Comment by bertfrees** [comment]
> It seems to put too many requirements on the client implementation.

Yes I understand the concern. There is (a) the question of how to validate and (b) the question of how to present options of certain types as widgets.

> I don't know how you would map a generic Relax NG structure to a Web UI widget?

I guess the client would have to recognize the basic types such as simple enumeration lists for which it wants to use special widgets. This is probably the most important challenge. For all other types it can fall back on a simple string input field and perform (possibly live) validation on it either using a RelaxNG implementation or by using a validation API of the Pipeline. The validation API has the benefit that it does not restrict us to RelaxNG or any syntax, and that it is available for clients written in any language.

> There is no id in RelaxNG, but I guess we could just add it anyway.

There is `<define name="foo">`.

> My main concern is that it must be easy for the Web UI to parse and do something with the datatypes.

Right. Any client could either just ignore the datatypes or at the minimum perform validation on the options before submitting the job, under the condition that we have a validation API. The web UI may be able to do something extra because it is Java so it can use Jing. 

But because (a) we don't have a validation API yet and (b) we haven't explored the possibilities of Jing yet, I suggest we start with the custom syntax described above: `/values[@id]/value/text()` for enums and `/regex[@id | @pattern]` for patterns. And we keep in mind supporting RelaxNG in addition to this custom syntax later.

**Comment by bertfrees** [comment]
Jostein and I discussed and in the end we went with:

**enum**: `/choice[@id]/value/text()` (Relax NG + root `@id`)

**regex**: `/data[@id]/param[@name='pattern']/text()` (Relax NG + root `@id`)

The idea is to have a (almost) subset of RelaxNG so that if we decide later to move to RelaxNG completely we are almost compatible.

One idea to support nice names on enum values is to add a `px:nicename` attribute on the `value` elements. Another idea is to have a `documentation` element as the first child of `choice`:

``` xml
<choice>
  <documentation xmlns="http://relaxng.org/ns/compatibility/annotations/1.0" xml:lang="en">
    <value>Nicename 1</value>
    <value>Nicename 2</value>
  </documentation>
  <value>value1</value>
  <value>value2</value>
</choice>
```

**Comment by bertfrees** [comment]
@usama49 When you are ready with the MTM script could you also have a look at https://github.com/daisy/pipeline-mod-braille/issues/26?

**Comment by bertfrees** [comment]
Scripts now have datatypes, either declared inline (https://github.com/daisy/pipeline-mod-braille/issues/85), or declared in a separate file and referenced from the script options. We're using the subset of RelaxNG decribed above, also with the solution described above for value descriptions, but we plan to change that to a better solution: https://github.com/daisy/pipeline-webui/issues/71.
